### ISSUE TITLE
Translations and Keyboard layout

### ISSUE THREAD

**Issue by Jerome-Herbinet** [hannahcode/word-guessing-game#106]
Hello,
First of all, thank you very much for your work; this little game is superb.
I have two suggestions for improvement.
1. Translation: when you choose a country (flag), it would be great if the page could be fully translated. If you wish, I can bring you all the necessary translations in French.
2. Depending on the country (flag) chosen, can the keyboard correspond to the country. For example, in France, the keyboard is AZERTY.
Thank you in advance.
I remain at your disposal!
Jérôme

**Comment by cwackerfuss** [comment]
Hi Jerome! Really appreciate the suggestion- Internationalization is probably outside the scope of this project in an effort to keep it simple for others to get up and running quickly without having to grok too much complexity. I think one of the reasons this repo has grown so much is that it's accessible for even novice engineers. Keep in mind some folks are also customizing this beyond letters, there are even versions with numbers (https://converged.yt/primel/).
