### ISSUE TITLE
What's the purpose of valid guesses array ?

### ISSUE THREAD

**Issue by aissa-bouguern** [hannahcode/word-guessing-game#107]
Can someone please explain what's the purpose of VALIDGUESSES array ?

**Comment by 7vueltas** [comment]
When you try with a word, only words in VALIDGUESSES array area valid. For example: if you try this word: "ABCDE" a window with a not valid word message is displayed because this word is not into VALIDGUESSES array-

**Comment by angelvilches** [comment]
When you try with a word, only words in VALIDGUESSES array area valid. For example: if you try this word: "ABCDE" a "not valid word" message is displayed because this word is not into VALIDGUESSES array-
