### ISSUE TITLE
Add a feature to store starting words

### ISSUE THREAD

**Issue by asirota** [hannahcode/word-guessing-game#74]
One strategy for Wordle is to use a starting word or two (or three!) to start a game. It would be nice To have a way to store a few of these for use. Would be even better to automatically play one/two/three of them right away.

**Comment by AnanthNatarajan** [comment]
Doesn't it take away some of the fun? I guess people want to type, not automate even that!

**Comment by cwackerfuss** [comment]
Hey @asirota, I think I agree with @AnanthNatarajan - probably not worth the effort and added complexity to the interface to include a feature like this to the main repo. Thanks for the suggestion 🙇
