### ISSUE TITLE
Removal of Wordle brand from application?

### ISSUE THREAD

**Issue by slyduda** [hannahcode/word-guessing-game#86]
With NYT's purchase of Wordle, they will no doubt file for trademark. I assume that they get legal precedent over anyone with the name Wordle in the app itself.

Since this is the largest clone repository I could find, may I suggest potentially going for a change in branding to keep this project alive!

**Comment by chessmango** [comment]
Pretty sure fixed by https://github.com/hannahcode/word-guessing-game/commit/ad4ecb2270760169e85ba766dc46ad93ba521006 and https://github.com/hannahcode/word-guessing-game/commit/ccb2bf404c709bcb74089e2fe2f14145b0b360f0

**Comment by nmstoker** [comment]
Make sure any new name doesn't sound like [Lingo](https://en.m.wikipedia.org/wiki/Lingo_(British_game_show)) either! 🙂
